name: Tag Release

on:
  pull_request:
    types: [closed]
    branches: [master]

jobs:
  tag:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Push release tag
        run: |
          version="${{ github.event.pull_request.head.ref }}"
          version="${version#release/}"
          git tag "$version"
          git push origin "$version"
